version: "3.8"
services:
  user-service:
    image: avaji/user-service-docker
    container_name: user-service
    ports:
      - 8081:8081
    restart: always


  article-service:
    image: avaji/arcticle-service-docker
    container_name: article-service
    ports:
      - 8082:8082
    restart: always

  app:
    image: avaji/api-geteway-docker
    container_name: application
    ports:
      - 8083:8083
    restart: always
    links:
      - user-service
      - article-service

  nginx:
    image: nginx:latest

    container_name: nginx
    ports:
      - 8080:8080
    restart: always
    volumes:
      - type: bind
        source: ./config.nginx
        target: /etc/nginx/conf.d
    links:
      - app